### ISSUE TITLE
Error: line contains NULL byte

### ISSUE THREAD

**Issue by stigoleg** [FOIA-data-hackathon/MuckRock-Caravel#1]
Hi,
I get this error when I try to run the script? Any ideas on how I can solve this?

```
./csv2sqlite.py ~/temp/*****/test.csv ~/temp/*****/test.db
Traceback (most recent call last):
  File "./csv2sqlite.py", line 198, in <module>
    convert(args.csv_file, args.sqlite_db_file, args.table_name, args.headers, compression)
  File "./csv2sqlite.py", line 66, in convert
    types = _guess_types(type_reader, len(headers))
  File "./csv2sqlite.py", line 140, in _guess_types
    for row_index,row in enumerate(reader):
_csv.Error: line contains NULL byte
```

**Comment by Miserlou** [comment]
Interesting! Let me see..

**Comment by Miserlou** [comment]
Is test.csv your own file, or the one described in the README? This seems relevant: http://stackoverflow.com/questions/4166070/python-csv-error-line-contains-null-byte

**Comment by stigoleg** [comment]
Hi, 
Thanks for the fast reply.
It's my own file. Might it be because the file does not contain headers?

---

EDIT: I added the headers and everything works. Thank you
