### ISSUE TITLE
Floats being converted to integer (Unable to convert value)

### ISSUE THREAD

**Issue by ryanjones** [FOIA-data-hackathon/MuckRock-Caravel#2]
I tried running this to create an SQLite DB from a CSV, but I'm getting this error for all of my floats (negative and positive). 

Unable to convert value '39.99' to type 'integer' on line 5304

Here's an example of the row:

```
2016-01-07 0:00,    16:15,  56: Edmonton Manning,   test,   test213,    test111,    0,  39.99,  <Unknown>,  <Unknowon>,     <Unknown>,  <Unknown>,  
```

I'll try and dig into the issue, but my python isn't very strong, any help would be much appreciated.

**Comment by Miserlou** [comment]
Ah, I'd move upstream for that issue: https://github.com/rgrp/csv2sqlite

**Comment by ryanjones** [comment]
Arg. Didn't notice that. Thanks!
